import {readFile,readdir} from 'node:fs/promises';
import {validateManifest} from '../compiler.mjs';
import {digest,LIMITS} from './limits.mjs';
const dependencies=Object.freeze({'@metaharness/kernel':'0.1.3','@ruvector/core':'0.1.32','@claude-flow/cli':'3.25.6','@modelcontextprotocol/server':'2.0.0','@modelcontextprotocol/client':'2.0.0','ruvector-core-linux-x64-gnu':'0.1.30'});
export async function planAgent(manifest){
 validateManifest(manifest);const files={};const base=new URL('./',import.meta.url);
 for(const name of (await readdir(base)).filter(n=>/^[a-z-]+\.mjs$/.test(n)).sort())files['src/agent/'+name]=await readFile(new URL(name,base),'utf8');
 files['src/compiler.mjs']=await readFile(new URL('../compiler.mjs',base),'utf8');files['agent.json']=JSON.stringify(manifest,null,2)+'\n';
 files['package.json']=JSON.stringify({name:'generated-metaharness-agent',version:'1.0.0',private:true,type:'module',engines:{node:'>=24'},scripts:{start:'node src/agent/runner.mjs run',mcp:'node src/agent/runner.mjs mcp',status:'node src/agent/runner.mjs status'},dependencies,overrides:{qs:'6.16.0'}},null,2)+'\n';
 const lock=JSON.parse(await readFile(new URL('../../package-lock.json',base),'utf8'));lock.name='generated-metaharness-agent';lock.version='1.0.0';lock.packages['']={name:lock.name,version:lock.version,dependencies,engines:{node:'>=24'}};files['package-lock.json']=JSON.stringify(lock,null,2)+'\n';
 files['.npmrc']='omit=optional\nignore-scripts=true\n';
 files['harness.json']=JSON.stringify({name:manifest.spec.name,agents:[{name:'agent',systemPrompt:manifest.messages[0].content}],mcpServers:[{name:'agent',command:['node','src/agent/runner.mjs','mcp']}],permissions:{allow:manifest.spec.tools,deny:['shell','filesystem','publish']},autonomous:{goal:{text:manifest.spec.purpose,tokenBudget:LIMITS.maxTurns*LIMITS.maxTokensPerTurn},maxTurns:LIMITS.maxTurns}},null,2)+'\n';
 files['README.md']='# Runnable MetaHarness agent\n\nThe qualified runtime is Linux x64 with Node24. Unused optional RuFlo integrations are omitted to avoid their vulnerable dependency trees. Install Node24 and run `npm ci` followed by `npm audit`. Configure a private absolute `BOT_AGENT_STORAGE`, `BOT_AGENT_ALLOW_LIVE=1`, dedicated `BOT_AGENT_API_KEY`, and explicit `BOT_AGENT_MODEL`. Send `{ "input": "your task" }` as stdin JSON to `npm start`. Run `npm run mcp` for the stdio MCP. No key is included.\n\nOptional `BOT_AGENT_RUFLO=1` invokes the pinned RuFlo keyword routing hook. Only approved `search` uses local native RuVector lexical memory; set `BOT_ALLOWED_TOOLS=search` when requested by the manifest. Content grants no tool authority. Four turns, four tools, 30 seconds, 512 requested completion tokens per turn are upper limits. There is no claim of model quality, self improvement or automatic deployment. Session receipts are unsigned hashes; output memory is private and scoped by agent manifest digest. Archive logs after128sessions. A stale writer.lock after a crash requires operator inspection and removal before resuming.\n';
 return {kind:'runnable-metaharness-agent',manifestSha256:manifest.sha256,files,fileHashes:Object.fromEntries(Object.entries(files).map(([name,content])=>[name,digest(content)])),dependencies,automaticPromotion:false,signed:false,executionAuthority:false};
}
